### ISSUE TITLE
Readme has duplicated example

### ISSUE THREAD

**Issue by curtisgibby** [josheby/yourls-advanced-reserved-urls#1]
You've got the first example line in the list twice.

```
- http://sho.rt/sample
- http://sho.rt/sample
```

I don't know if you intended these two lines to be different, but as it stands now, one of them should just be deleted.

**Comment by curtisgibby** [comment]
By the way, this is a great addition to the core YOURLS functionality. I originally assumed that the standard `$yourls_reserved_URL` did this by default, and was unpleasantly surprised when one of my clients pointed out that my server gave back a keyword containing a certain 4-letter F word.

**Comment by josheby** [comment]
Fixed.  I think it was supposed to have mixed case.  Thank you for the kind words and bringing the issue to my attention.
